name: Hugo build

env:
  WC_HUGO_VERSION: '0.126.3'

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  #nightly to keep statistics updated
  schedule:
    - cron:  '12 0 * * *'

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout Kaoto
        uses: actions/checkout@v4
        with:
          repository: 'KaotoIO/kaoto'
          path: 'tmp/kaoto'
          fetch-depth: '0'

      - name: Install Python dependencies
        run: pip3 install PyGithub
          
      - name: Generate Releases and Milestones
        run: python3 getGithubData.py $username $password
        env:
          username: ${{ secrets.API_USER }}
          password: ${{ secrets.API_PASSWORD }}
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup CNAME correctly
        if: always()
        run:  cp CNAME public/CNAME
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
    
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
    
      - name: Generate Pagefind search index
        run: npx pagefind --source "public"
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      -
        name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: public
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
